### PR TITLE
bz17793: Redirect stderr/stdout on Windows.

### PR DESCRIPTION
**Pull request by geoffl**
Try to write to a place we have permissions to rather than the current
directory of the binary which we might not have access to.

### CODE REVIEW

**Comment by bendk** [comment]
So duplicating the logging module is definitely bad.  Could we reset sys.stderr back to devnull when we start the logging code?  One more question, what happens in console mode?  We want mirodebug.exe to print stuff to stdout.

**Comment by geoffl** [comment]
okay, I agree that's a better way.  So let's setup a log but set it to devnull when we start the module.

When you run mirodebug.exe with the --unittest flag it runs a different startup() so it should not be an issue.

**Comment by bendk** [comment]
I think mirodebug is also used in the run.sh script.  It's built to run in console mode so that stdout actually does work.  I use it to run miro on windows and see the output of the logs without using tail or something like that.

**Comment by paulswartz** [comment]
Changes look good.

**Pull request merged**
