### PR TITLE
bz18895. don't create .miro on hidden devices

### PR DESCRIPTION
**Pull request by paulswartz**

### CODE REVIEW

**Comment by bendk** [comment]
I think this is okay, but it seems a bit un-clean to modify the path attribute like that.  Seems like the LiveStorage constructor could get an argument that makes it start in temp mode, and not try to switch out of it.

However, that solution is more complicated.  If this has been well tested, then I'm okay doing it for the release, and making a TODO to clean things up better.

What do you think paul?

**Comment by paulswartz** [comment]
No, I think that's a better fix.  I'll make that change today.

**Comment by paulswartz** [comment]
Implemented a `start_in_temp_mode` for LiveStorage.

**Comment by bendk** [comment]
The start_in_temp_mode change looks correct, but are we getting the same behavior afterwards?  Will it try to save the directory when the temp mode timeout stops?

After I wrote that I'm wondering if it still does the right thing because the .miro directory is not in place yet, so the attempt fails.  If so, that seems fine but a comment would be good.

**Comment by paulswartz** [comment]
It doesn't create the .miro directory at first because we're setting `force_directory_creation` to `False` before the directory is created.  Once the device is shown, we create the directory and switch out of temporary mode.

**Comment by bendk** [comment]
Looks great.  Merging.

**Pull request merged**
