### PR TITLE
Menuchanges3

### PR DESCRIPTION
**Pull request by bendk**
Basically the menuchange2 with fixes for the issues paul pointed out.

### CODE REVIEW

**Comment by paulswartz** [comment]
Looks like it picked up some changes from me again.

**Comment by bendk** [comment]
Argh,  one day I'll learn how to use github.

**Comment by paulswartz** [comment]
Github will show you the commits in the merge before you open the request, if you click the names of the branches before you open the request.

**Comment by paulswartz** [comment]
Looks good, tests pass. Merging.

**Pull request merged**
