### PR TITLE
Bz18446

### PR DESCRIPTION
**Pull request by geoffl**
Some performance changes.  There's a mixed bag of cleanups and performance changes in there, but majorly:

break off batched adding videos into smaller chunks to improve responsiveness
move the metadata extractor into subprocess
yield to process other work when we are parsing a large directory in watched folders
save parasitic cpu usage with animated gif images
defer loading right hand side displays for a very short period of time.  Loading it is very expensive and during keyboard navigation the program can get clogged

### CODE REVIEW

**Comment by bendk** [comment]
Geoff: I think you've pulled a ben and added a lot of extra commits to this pull request.  Can you try rebasing with master?

I checked from the bottom of the list until rework find_new_children() and it all looks good, except for one typo.

**Comment by geoffl** [comment]
the comment has been fixed.  As for the extraneous commits not prefixed by bz18446, they really are part of this branch, part of some code cleanups I did separated into separate commits for clarity, so I think we are good to go.

**Comment by bendk** [comment]
Ahh, I got confused because I already reviewed some of these commits before.  I'm pretty sure I looked at everything starting with a18c4ae.  If you haven't made any extra changes to those commits in the last few days, then this change is good to go and you should merge it.  If you have made changes, I can take another pass at them.

**Comment by bendk** [comment]
I'm going to assume I was right and merge this one.  I'd love to start using this as a basis for the work I'm doing with mutagen, echonest, and metadata in general.

**Pull request merged**
