### PR TITLE
bz18854. upgrade libtorrent to 0.15.10

### PR DESCRIPTION
**Pull request by paulswartz**
The real change is in the binary kit:
http://git.participatoryculture.org/miro-binary-kit-win/commit/?id=87c8864c0834da04d58ea4bdeb54c08ea06199ff

### CODE REVIEW

**Comment by geoffl** [comment]
was this meant to be mac + windows or just windows only?

**Comment by paulswartz** [comment]
This is just for Windows, but I'll make another request for OS X.

**Comment by paulswartz** [comment]
And by 'another request', I mean update this one.

**Comment by bendk** [comment]
Looks great.

**Pull request merged**
